### ISSUE TITLE
[Task] Implement InMemoryStrategy for Model Resolution

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-esmf/esmf-sdk#299]
The documentation mentions an [InMemoryStrategy](https://openmanufacturingplatform.github.io/sds-documentation/sds-developer-guide/tooling-guide/java-aspect-tooling.html#understanding-model-resolution) to parse SAMM-models. I think that's a very useful feature as it would allow to switch between plain RDF and SAMM meta-model objects.

The class however is nowhere to be found in this repository. Looking for related Issues didn't bring up anything either. Regardless if the feature was removed or never implemented, having it would be great.

**Comment by atextor** [comment]
Hi @arnoweiss,
this class existed when the system for model resolution was quite different than it is now and was removed during its refactoring. Still mentioning it in the documentation was an oversight that has been fixed in #290. However, I agree it would be useful to have also in the new model resolution system, so let's reintroduce it, this time with proper documentation.

**Comment by atextor** [comment]
Fixed in https://github.com/eclipse-esmf/esmf-sdk/commit/06b62fc3c2ee52aa9a5946340043801e0aadf085
