### ISSUE TITLE
[BUG] HTML Doc: enumerations displayed as "value.getValue"

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-esmf/esmf-sdk#323]
**Describe the bug**
In case of enumeration with string values html documentation does not display the value but the operation $value.getValue() per value in the enumeration. The example value is "$property.getExampleValue().get().getValue()"

Instead the values should be displayed themselves.

**Where**
Indicate the location of the bug (e.g., which component of the SDK, which API call, which command etc.).

**Screenshots**
![grafik](https://user-images.githubusercontent.com/59824205/224705077-4950b6e9-f369-40ef-8be5-781b3d0d1330.png)

![grafik](https://user-images.githubusercontent.com/59824205/224705384-e85bcdc1-9b00-4533-b7ee-b3de66a5f5f9.png)

**Comment by chris-volk** [comment]
Hi @BirgitBoss , which version was used, and which example ttl produces this issue?

**Comment by michelu89** [comment]
I encountered this problem while working with the SAMM-CLI v2.2.1 in the native-image environment. The issue involves the incorrect resolution of the ExampleValue, resulting in unexpected behavior. I have successfully reproduced the problem and captured screenshots to illustrate the issue.

Steps to Reproduce:

1. Download the SAMM-CLI v2.2.1 NATIVE-IMAGE for Windows/Linux.
2. Execute the command: **_./samm.exe aspect "FILE_TO_ASPECT" to html_**
3. Observe the resolution of ExampleValue. (All other placeholders are working well)

**Expected Behavior:**
The ExampleValue should be resolved correctly, providing the expected result in the native-image environment.

**Actual Behavior:**
The ExampleValue is not resolved correctly in the native-image environment, leading to unexpected out.

![HTML_GENERATION_EXAMPLE](https://github.com/eclipse-esmf/esmf-sdk/assets/10807610/5755ad19-853e-4cd2-aea6-2cec31e1d7f8)
