### ISSUE TITLE
[BUG] Example JSON generated with SAMM CLI does not validate against generated JSON Schema

### ISSUE THREAD

**Issue by bs-jokri** [eclipse-esmf/esmf-sdk#372]
**Describe the bug**
the generated example json and schema for model
https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.fleet.claim_data/1.0.0/ClaimData.ttl

to be found here
https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.fleet.claim_data/1.0.0/gen

did not validate against the published generated schema.

**Where**
Artifacts generated with BAMM-cLI 2.1.3

**Comment by atextor** [comment]
Note that the JSON generation was fixed in regards to wrong structures for sets (leading to the _should be array_ validation messages) and for example values that use the `rdf:langString` datattype. However, for the PCF 4.0.0 model, JSON Schema validation will still fail due to [an error](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.pcf/4.0.0/Pcf.ttl#L123) in the model:

```turtle
bamm:exampleValue "0"^^xsd:positiveInteger.
```

0 is not a valid value in for `xsd:positiveInteger`.

Similarly, JSON Schema validation will fail for ClaimData.ttl, because the [example value provided](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.fleet.claim_data/1.0.0/ClaimData.ttl#L139) for `:vehicleCatenaXId`:
```turtle
bamm:exampleValue "580d3adf-1981-44a0-a214" .
```
does not actually correspond to the [regular expression](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.fleet.claim_data/1.0.0/ClaimData.ttl#L227) that is used in the [`:CatenaXIdTrait`](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.fleet.claim_data/1.0.0/ClaimData.ttl#L168).

Improved validation of values for `samm:exampleValue` will be adressed in #384.
