### ISSUE TITLE
[BUG] Descriptions missing in generated JSON Schema

### ISSUE THREAD

**Issue by chris-volk** [eclipse-esmf/esmf-sdk#446]
When creating a JSON Schema with SAMM-cli 2.3.2, in some cases the description of elements appears to be missing in the generated artefact.
It was reported to us that this is a regression since SAMM-cli 2.1.1.

**Comment by Yauhenikapl** [comment]
Hi @chris-volk ,

maybe you have the opportunity to provide an example the **.ttl** file in which this behavior occurs, since I have done several checks: _debug_, _.jar_ file and _samm-cli executable file_ with its test aspect and have not yet been able to reproduce this behavior..?

Thanks,
Best Regards!

**Comment by chris-volk** [comment]
The user has create an invalid ttl file with multiple description entries for the same language (@en). 
As a result one of them could not be shown in the generated JSON Schema.
A validation via SAMM CLI revealed this issue with the input file.
We cannot reproduce a scenario where a description is missing in the JSON Schema. Closing this issue.
