### ISSUE TITLE
[BUG] SAMM-CLI aas generation: aas:ConceptDescription for samm:Property gets aas:idShort based on samm:Characteristic.name

### ISSUE THREAD

**Issue by mhmmi** [eclipse-esmf/esmf-sdk#457]
**Describe the bug**
When creating AAS files with SAMM-CLI: An aas:ConceptDescription for a samm:Property gets an aas:idShort based on its samm:Characteristic.name instead of the samm:Property. The same applies to the aas:displayName. While this is not explicitly defined in https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/java-aspect-tooling.html#mapping-aas, I think it's wrong, as the aas:ConceptDescription describes the aas:Property (or aas:SubmodelElement in general). In particular, this creates ambiguous aas:idShorts when a samm:Characteristic is used multiple times.

**Where**
When creating AAS files with SAMM-CLI

**Screenshots**
-/-

**Additional context**
-/-

**Comment by chris-volk** [comment]
Dear @mhmmi , thanks for taking the time to provide this and the other bug reports.

**Comment by chris-volk** [comment]
Mapping improvements from Property(/Characteristic) to ConceptDescription will be considered together with https://github.com/eclipse-esmf/esmf-sdk/issues/434

**Comment by Yauhenikapl** [comment]
Hi,

After some discussion with @BirgitBoss @chris-volk @atextor @KobOp we agreed with this [PR: SAMM-CLI aas generation](https://github.com/eclipse-esmf/esmf-sdk/pull/483)

NOTE:
The source of a ConceptDescription is only a Property and not a Characteristic since as of Dec 2023 ConceptDescriptions are 'only' properties as in IEC61360.

Thanks,
Best Regards!
